// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.13.0
// source: testdata/proto/test.proto

package series

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Kubernetes struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Kubernetes) Reset() {
	*x = Kubernetes{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_proto_test_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Kubernetes) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kubernetes) ProtoMessage() {}

func (x *Kubernetes) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_test_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kubernetes.ProtoReflect.Descriptor instead.
func (*Kubernetes) Descriptor() ([]byte, []int) {
	return file_testdata_proto_test_proto_rawDescGZIP(), []int{0}
}

type Kubernetes_Node struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Kubernetes_Node) Reset() {
	*x = Kubernetes_Node{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_proto_test_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Kubernetes_Node) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kubernetes_Node) ProtoMessage() {}

func (x *Kubernetes_Node) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_test_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kubernetes_Node.ProtoReflect.Descriptor instead.
func (*Kubernetes_Node) Descriptor() ([]byte, []int) {
	return file_testdata_proto_test_proto_rawDescGZIP(), []int{0, 0}
}

type Kubernetes_PodNetwork struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Kubernetes_PodNetwork) Reset() {
	*x = Kubernetes_PodNetwork{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_proto_test_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Kubernetes_PodNetwork) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kubernetes_PodNetwork) ProtoMessage() {}

func (x *Kubernetes_PodNetwork) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_test_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kubernetes_PodNetwork.ProtoReflect.Descriptor instead.
func (*Kubernetes_PodNetwork) Descriptor() ([]byte, []int) {
	return file_testdata_proto_test_proto_rawDescGZIP(), []int{0, 1}
}

type Kubernetes_PodVolume struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Kubernetes_PodVolume) Reset() {
	*x = Kubernetes_PodVolume{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_proto_test_proto_msgTypes[3]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Kubernetes_PodVolume) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kubernetes_PodVolume) ProtoMessage() {}

func (x *Kubernetes_PodVolume) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_test_proto_msgTypes[3]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kubernetes_PodVolume.ProtoReflect.Descriptor instead.
func (*Kubernetes_PodVolume) Descriptor() ([]byte, []int) {
	return file_testdata_proto_test_proto_rawDescGZIP(), []int{0, 2}
}

type Kubernetes_PodContainer struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields
}

func (x *Kubernetes_PodContainer) Reset() {
	*x = Kubernetes_PodContainer{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_proto_test_proto_msgTypes[4]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Kubernetes_PodContainer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kubernetes_PodContainer) ProtoMessage() {}

func (x *Kubernetes_PodContainer) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_test_proto_msgTypes[4]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kubernetes_PodContainer.ProtoReflect.Descriptor instead.
func (*Kubernetes_PodContainer) Descriptor() ([]byte, []int) {
	return file_testdata_proto_test_proto_rawDescGZIP(), []int{0, 3}
}

type Kubernetes_Node_Tag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeName string `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
}

func (x *Kubernetes_Node_Tag) Reset() {
	*x = Kubernetes_Node_Tag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_proto_test_proto_msgTypes[5]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Kubernetes_Node_Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kubernetes_Node_Tag) ProtoMessage() {}

func (x *Kubernetes_Node_Tag) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_test_proto_msgTypes[5]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kubernetes_Node_Tag.ProtoReflect.Descriptor instead.
func (*Kubernetes_Node_Tag) Descriptor() ([]byte, []int) {
	return file_testdata_proto_test_proto_rawDescGZIP(), []int{0, 0, 0}
}

func (x *Kubernetes_Node_Tag) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

type Kubernetes_Node_Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CpuUsageCoreNanoseconds int64 `protobuf:"varint,1,opt,name=cpu_usage_core_nanoseconds,json=cpuUsageCoreNanoseconds,proto3" json:"cpu_usage_core_nanoseconds,omitempty"`
	MemoryAvailableBytes    int64 `protobuf:"varint,2,opt,name=memory_available_bytes,json=memoryAvailableBytes,proto3" json:"memory_available_bytes,omitempty"`
}

func (x *Kubernetes_Node_Field) Reset() {
	*x = Kubernetes_Node_Field{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_proto_test_proto_msgTypes[6]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Kubernetes_Node_Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kubernetes_Node_Field) ProtoMessage() {}

func (x *Kubernetes_Node_Field) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_test_proto_msgTypes[6]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kubernetes_Node_Field.ProtoReflect.Descriptor instead.
func (*Kubernetes_Node_Field) Descriptor() ([]byte, []int) {
	return file_testdata_proto_test_proto_rawDescGZIP(), []int{0, 0, 1}
}

func (x *Kubernetes_Node_Field) GetCpuUsageCoreNanoseconds() int64 {
	if x != nil {
		return x.CpuUsageCoreNanoseconds
	}
	return 0
}

func (x *Kubernetes_Node_Field) GetMemoryAvailableBytes() int64 {
	if x != nil {
		return x.MemoryAvailableBytes
	}
	return 0
}

type Kubernetes_PodNetwork_Tag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	NodeName  string `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	PodName   string `protobuf:"bytes,3,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
}

func (x *Kubernetes_PodNetwork_Tag) Reset() {
	*x = Kubernetes_PodNetwork_Tag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_proto_test_proto_msgTypes[7]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Kubernetes_PodNetwork_Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kubernetes_PodNetwork_Tag) ProtoMessage() {}

func (x *Kubernetes_PodNetwork_Tag) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_test_proto_msgTypes[7]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kubernetes_PodNetwork_Tag.ProtoReflect.Descriptor instead.
func (*Kubernetes_PodNetwork_Tag) Descriptor() ([]byte, []int) {
	return file_testdata_proto_test_proto_rawDescGZIP(), []int{0, 1, 0}
}

func (x *Kubernetes_PodNetwork_Tag) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Kubernetes_PodNetwork_Tag) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *Kubernetes_PodNetwork_Tag) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

type Kubernetes_PodNetwork_Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	RxBytes  int64 `protobuf:"varint,1,opt,name=rx_bytes,json=rxBytes,proto3" json:"rx_bytes,omitempty"`
	RxErrors int64 `protobuf:"varint,2,opt,name=rx_errors,json=rxErrors,proto3" json:"rx_errors,omitempty"`
}

func (x *Kubernetes_PodNetwork_Field) Reset() {
	*x = Kubernetes_PodNetwork_Field{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_proto_test_proto_msgTypes[8]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Kubernetes_PodNetwork_Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kubernetes_PodNetwork_Field) ProtoMessage() {}

func (x *Kubernetes_PodNetwork_Field) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_test_proto_msgTypes[8]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kubernetes_PodNetwork_Field.ProtoReflect.Descriptor instead.
func (*Kubernetes_PodNetwork_Field) Descriptor() ([]byte, []int) {
	return file_testdata_proto_test_proto_rawDescGZIP(), []int{0, 1, 1}
}

func (x *Kubernetes_PodNetwork_Field) GetRxBytes() int64 {
	if x != nil {
		return x.RxBytes
	}
	return 0
}

func (x *Kubernetes_PodNetwork_Field) GetRxErrors() int64 {
	if x != nil {
		return x.RxErrors
	}
	return 0
}

type Kubernetes_PodVolume_Tag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Namespace  string `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	NodeName   string `protobuf:"bytes,2,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	PodName    string `protobuf:"bytes,3,opt,name=pod_name,json=podName,proto3" json:"pod_name,omitempty"`
	VolumeName string `protobuf:"bytes,4,opt,name=volume_name,json=volumeName,proto3" json:"volume_name,omitempty"`
}

func (x *Kubernetes_PodVolume_Tag) Reset() {
	*x = Kubernetes_PodVolume_Tag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_proto_test_proto_msgTypes[9]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Kubernetes_PodVolume_Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kubernetes_PodVolume_Tag) ProtoMessage() {}

func (x *Kubernetes_PodVolume_Tag) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_test_proto_msgTypes[9]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kubernetes_PodVolume_Tag.ProtoReflect.Descriptor instead.
func (*Kubernetes_PodVolume_Tag) Descriptor() ([]byte, []int) {
	return file_testdata_proto_test_proto_rawDescGZIP(), []int{0, 2, 0}
}

func (x *Kubernetes_PodVolume_Tag) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *Kubernetes_PodVolume_Tag) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *Kubernetes_PodVolume_Tag) GetPodName() string {
	if x != nil {
		return x.PodName
	}
	return ""
}

func (x *Kubernetes_PodVolume_Tag) GetVolumeName() string {
	if x != nil {
		return x.VolumeName
	}
	return ""
}

type Kubernetes_PodVolume_Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	AvailableBytes int64 `protobuf:"varint,1,opt,name=available_bytes,json=availableBytes,proto3" json:"available_bytes,omitempty"`
	CapacityBytes  int64 `protobuf:"varint,2,opt,name=capacity_bytes,json=capacityBytes,proto3" json:"capacity_bytes,omitempty"`
	UsedBytes      int64 `protobuf:"varint,3,opt,name=used_bytes,json=usedBytes,proto3" json:"used_bytes,omitempty"`
}

func (x *Kubernetes_PodVolume_Field) Reset() {
	*x = Kubernetes_PodVolume_Field{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_proto_test_proto_msgTypes[10]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Kubernetes_PodVolume_Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kubernetes_PodVolume_Field) ProtoMessage() {}

func (x *Kubernetes_PodVolume_Field) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_test_proto_msgTypes[10]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kubernetes_PodVolume_Field.ProtoReflect.Descriptor instead.
func (*Kubernetes_PodVolume_Field) Descriptor() ([]byte, []int) {
	return file_testdata_proto_test_proto_rawDescGZIP(), []int{0, 2, 1}
}

func (x *Kubernetes_PodVolume_Field) GetAvailableBytes() int64 {
	if x != nil {
		return x.AvailableBytes
	}
	return 0
}

func (x *Kubernetes_PodVolume_Field) GetCapacityBytes() int64 {
	if x != nil {
		return x.CapacityBytes
	}
	return 0
}

func (x *Kubernetes_PodVolume_Field) GetUsedBytes() int64 {
	if x != nil {
		return x.UsedBytes
	}
	return 0
}

type Kubernetes_PodContainer_Tag struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	NodeName      string `protobuf:"bytes,1,opt,name=node_name,json=nodeName,proto3" json:"node_name,omitempty"`
	ContainerName string `protobuf:"bytes,2,opt,name=container_name,json=containerName,proto3" json:"container_name,omitempty"`
}

func (x *Kubernetes_PodContainer_Tag) Reset() {
	*x = Kubernetes_PodContainer_Tag{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_proto_test_proto_msgTypes[11]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Kubernetes_PodContainer_Tag) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kubernetes_PodContainer_Tag) ProtoMessage() {}

func (x *Kubernetes_PodContainer_Tag) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_test_proto_msgTypes[11]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kubernetes_PodContainer_Tag.ProtoReflect.Descriptor instead.
func (*Kubernetes_PodContainer_Tag) Descriptor() ([]byte, []int) {
	return file_testdata_proto_test_proto_rawDescGZIP(), []int{0, 3, 0}
}

func (x *Kubernetes_PodContainer_Tag) GetNodeName() string {
	if x != nil {
		return x.NodeName
	}
	return ""
}

func (x *Kubernetes_PodContainer_Tag) GetContainerName() string {
	if x != nil {
		return x.ContainerName
	}
	return ""
}

type Kubernetes_PodContainer_Field struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	CpuUsageCoreNanoseconds int64 `protobuf:"varint,1,opt,name=cpu_usage_core_nanoseconds,json=cpuUsageCoreNanoseconds,proto3" json:"cpu_usage_core_nanoseconds,omitempty"`
	MemoryUsageBytes        int64 `protobuf:"varint,2,opt,name=memory_usage_bytes,json=memoryUsageBytes,proto3" json:"memory_usage_bytes,omitempty"`
}

func (x *Kubernetes_PodContainer_Field) Reset() {
	*x = Kubernetes_PodContainer_Field{}
	if protoimpl.UnsafeEnabled {
		mi := &file_testdata_proto_test_proto_msgTypes[12]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Kubernetes_PodContainer_Field) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Kubernetes_PodContainer_Field) ProtoMessage() {}

func (x *Kubernetes_PodContainer_Field) ProtoReflect() protoreflect.Message {
	mi := &file_testdata_proto_test_proto_msgTypes[12]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Kubernetes_PodContainer_Field.ProtoReflect.Descriptor instead.
func (*Kubernetes_PodContainer_Field) Descriptor() ([]byte, []int) {
	return file_testdata_proto_test_proto_rawDescGZIP(), []int{0, 3, 1}
}

func (x *Kubernetes_PodContainer_Field) GetCpuUsageCoreNanoseconds() int64 {
	if x != nil {
		return x.CpuUsageCoreNanoseconds
	}
	return 0
}

func (x *Kubernetes_PodContainer_Field) GetMemoryUsageBytes() int64 {
	if x != nil {
		return x.MemoryUsageBytes
	}
	return 0
}

var File_testdata_proto_test_proto protoreflect.FileDescriptor

var file_testdata_proto_test_proto_rawDesc = []byte{
	0x0a, 0x19, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74, 0x61, 0x2f, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x2f, 0x74, 0x65, 0x73, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0xb6, 0x06, 0x0a, 0x0a,
	0x4b, 0x75, 0x62, 0x65, 0x72, 0x6e, 0x65, 0x74, 0x65, 0x73, 0x1a, 0xa6, 0x01, 0x0a, 0x04, 0x4e,
	0x6f, 0x64, 0x65, 0x1a, 0x22, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f,
	0x64, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e,
	0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x7a, 0x0a, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64,
	0x12, 0x3b, 0x0a, 0x1a, 0x63, 0x70, 0x75, 0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f,
	0x72, 0x65, 0x5f, 0x6e, 0x61, 0x6e, 0x6f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x03, 0x52, 0x17, 0x63, 0x70, 0x75, 0x55, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f,
	0x72, 0x65, 0x4e, 0x61, 0x6e, 0x6f, 0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x34, 0x0a,
	0x16, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x5f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c,
	0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x14, 0x6d,
	0x65, 0x6d, 0x6f, 0x72, 0x79, 0x41, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x79,
	0x74, 0x65, 0x73, 0x1a, 0xaa, 0x01, 0x0a, 0x0a, 0x50, 0x6f, 0x64, 0x4e, 0x65, 0x74, 0x77, 0x6f,
	0x72, 0x6b, 0x1a, 0x5b, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d,
	0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61,
	0x6d, 0x65, 0x73, 0x70, 0x61, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65,
	0x4e, 0x61, 0x6d, 0x65, 0x12, 0x19, 0x0a, 0x08, 0x70, 0x6f, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x52, 0x07, 0x70, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x1a,
	0x3f, 0x0a, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x19, 0x0a, 0x08, 0x72, 0x78, 0x5f, 0x62,
	0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x07, 0x72, 0x78, 0x42, 0x79,
	0x74, 0x65, 0x73, 0x12, 0x1b, 0x0a, 0x09, 0x72, 0x78, 0x5f, 0x65, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x08, 0x72, 0x78, 0x45, 0x72, 0x72, 0x6f, 0x72, 0x73,
	0x1a, 0x81, 0x02, 0x0a, 0x09, 0x50, 0x6f, 0x64, 0x56, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x1a, 0x7c,
	0x0a, 0x03, 0x54, 0x61, 0x67, 0x12, 0x1c, 0x0a, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70, 0x61,
	0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x09, 0x6e, 0x61, 0x6d, 0x65, 0x73, 0x70,
	0x61, 0x63, 0x65, 0x12, 0x1b, 0x0a, 0x09, 0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65,
	0x12, 0x19, 0x0a, 0x08, 0x70, 0x6f, 0x64, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01,
	0x28, 0x09, 0x52, 0x07, 0x70, 0x6f, 0x64, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x76,
	0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0a, 0x76, 0x6f, 0x6c, 0x75, 0x6d, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x1a, 0x76, 0x0a, 0x05,
	0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x27, 0x0a, 0x0f, 0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62,
	0x6c, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0e,
	0x61, 0x76, 0x61, 0x69, 0x6c, 0x61, 0x62, 0x6c, 0x65, 0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x25,
	0x0a, 0x0e, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0d, 0x63, 0x61, 0x70, 0x61, 0x63, 0x69, 0x74, 0x79,
	0x42, 0x79, 0x74, 0x65, 0x73, 0x12, 0x1d, 0x0a, 0x0a, 0x75, 0x73, 0x65, 0x64, 0x5f, 0x62, 0x79,
	0x74, 0x65, 0x73, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x52, 0x09, 0x75, 0x73, 0x65, 0x64, 0x42,
	0x79, 0x74, 0x65, 0x73, 0x1a, 0xcd, 0x01, 0x0a, 0x0c, 0x50, 0x6f, 0x64, 0x43, 0x6f, 0x6e, 0x74,
	0x61, 0x69, 0x6e, 0x65, 0x72, 0x1a, 0x49, 0x0a, 0x03, 0x54, 0x61, 0x67, 0x12, 0x1b, 0x0a, 0x09,
	0x6e, 0x6f, 0x64, 0x65, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x08, 0x6e, 0x6f, 0x64, 0x65, 0x4e, 0x61, 0x6d, 0x65, 0x12, 0x25, 0x0a, 0x0e, 0x63, 0x6f, 0x6e,
	0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x5f, 0x6e, 0x61, 0x6d, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28,
	0x09, 0x52, 0x0d, 0x63, 0x6f, 0x6e, 0x74, 0x61, 0x69, 0x6e, 0x65, 0x72, 0x4e, 0x61, 0x6d, 0x65,
	0x1a, 0x72, 0x0a, 0x05, 0x46, 0x69, 0x65, 0x6c, 0x64, 0x12, 0x3b, 0x0a, 0x1a, 0x63, 0x70, 0x75,
	0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x63, 0x6f, 0x72, 0x65, 0x5f, 0x6e, 0x61, 0x6e, 0x6f,
	0x73, 0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x17, 0x63,
	0x70, 0x75, 0x55, 0x73, 0x61, 0x67, 0x65, 0x43, 0x6f, 0x72, 0x65, 0x4e, 0x61, 0x6e, 0x6f, 0x73,
	0x65, 0x63, 0x6f, 0x6e, 0x64, 0x73, 0x12, 0x2c, 0x0a, 0x12, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79,
	0x5f, 0x75, 0x73, 0x61, 0x67, 0x65, 0x5f, 0x62, 0x79, 0x74, 0x65, 0x73, 0x18, 0x02, 0x20, 0x01,
	0x28, 0x03, 0x52, 0x10, 0x6d, 0x65, 0x6d, 0x6f, 0x72, 0x79, 0x55, 0x73, 0x61, 0x67, 0x65, 0x42,
	0x79, 0x74, 0x65, 0x73, 0x42, 0x12, 0x5a, 0x10, 0x2f, 0x74, 0x65, 0x73, 0x74, 0x64, 0x61, 0x74,
	0x61, 0x2f, 0x73, 0x65, 0x72, 0x69, 0x65, 0x73, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_testdata_proto_test_proto_rawDescOnce sync.Once
	file_testdata_proto_test_proto_rawDescData = file_testdata_proto_test_proto_rawDesc
)

func file_testdata_proto_test_proto_rawDescGZIP() []byte {
	file_testdata_proto_test_proto_rawDescOnce.Do(func() {
		file_testdata_proto_test_proto_rawDescData = protoimpl.X.CompressGZIP(file_testdata_proto_test_proto_rawDescData)
	})
	return file_testdata_proto_test_proto_rawDescData
}

var file_testdata_proto_test_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_testdata_proto_test_proto_goTypes = []interface{}{
	(*Kubernetes)(nil),                    // 0: Kubernetes
	(*Kubernetes_Node)(nil),               // 1: Kubernetes.Node
	(*Kubernetes_PodNetwork)(nil),         // 2: Kubernetes.PodNetwork
	(*Kubernetes_PodVolume)(nil),          // 3: Kubernetes.PodVolume
	(*Kubernetes_PodContainer)(nil),       // 4: Kubernetes.PodContainer
	(*Kubernetes_Node_Tag)(nil),           // 5: Kubernetes.Node.Tag
	(*Kubernetes_Node_Field)(nil),         // 6: Kubernetes.Node.Field
	(*Kubernetes_PodNetwork_Tag)(nil),     // 7: Kubernetes.PodNetwork.Tag
	(*Kubernetes_PodNetwork_Field)(nil),   // 8: Kubernetes.PodNetwork.Field
	(*Kubernetes_PodVolume_Tag)(nil),      // 9: Kubernetes.PodVolume.Tag
	(*Kubernetes_PodVolume_Field)(nil),    // 10: Kubernetes.PodVolume.Field
	(*Kubernetes_PodContainer_Tag)(nil),   // 11: Kubernetes.PodContainer.Tag
	(*Kubernetes_PodContainer_Field)(nil), // 12: Kubernetes.PodContainer.Field
}
var file_testdata_proto_test_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_testdata_proto_test_proto_init() }
func file_testdata_proto_test_proto_init() {
	if File_testdata_proto_test_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_testdata_proto_test_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Kubernetes); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_proto_test_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Kubernetes_Node); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_proto_test_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Kubernetes_PodNetwork); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_proto_test_proto_msgTypes[3].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Kubernetes_PodVolume); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_proto_test_proto_msgTypes[4].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Kubernetes_PodContainer); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_proto_test_proto_msgTypes[5].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Kubernetes_Node_Tag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_proto_test_proto_msgTypes[6].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Kubernetes_Node_Field); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_proto_test_proto_msgTypes[7].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Kubernetes_PodNetwork_Tag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_proto_test_proto_msgTypes[8].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Kubernetes_PodNetwork_Field); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_proto_test_proto_msgTypes[9].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Kubernetes_PodVolume_Tag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_proto_test_proto_msgTypes[10].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Kubernetes_PodVolume_Field); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_proto_test_proto_msgTypes[11].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Kubernetes_PodContainer_Tag); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_testdata_proto_test_proto_msgTypes[12].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Kubernetes_PodContainer_Field); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_testdata_proto_test_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_testdata_proto_test_proto_goTypes,
		DependencyIndexes: file_testdata_proto_test_proto_depIdxs,
		MessageInfos:      file_testdata_proto_test_proto_msgTypes,
	}.Build()
	File_testdata_proto_test_proto = out.File
	file_testdata_proto_test_proto_rawDesc = nil
	file_testdata_proto_test_proto_goTypes = nil
	file_testdata_proto_test_proto_depIdxs = nil
}
